In [ ]:
import numpy as np #Importing numpy

In [ ]:
print("18IT092")
np.empty([2,2],dtype=int) #creating a blanck array


18IT092


array([[1, 1],
       [1, 0]])

In [ ]:
print("18IT092")
np.array([1,2,3]) #predefined data


18IT092


array([1, 2, 3])

In [ ]:
print("18IT092")
np.random.rand(4,4) #patternspecific

18IT092


array([[0.49395033, 0.86708339, 0.26788814, 0.90002716],
       [0.96747259, 0.27639084, 0.80223003, 0.15039125],
       [0.60656437, 0.50095822, 0.79138378, 0.36931487],
       [0.05867024, 0.87427121, 0.19859456, 0.07999506]])

In [ ]:
print("18IT092")
np.ones((4,2),dtype=int) #patternspecific

18IT092


array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

Slicing and updating elements


In [ ]:
print("18IT092")
a = np.array([1,2,3,2,1,5,2,4,2])
np.sort(a)
print(a.ndim,a.size,a.shape)
a = a.reshape(3,3)
b = np.random.rand(a.shape[0],a.shape[1])
c = np.concatenate((a,b))
print(c.ndim,c.size,c.shape)
b.reshape(1,9)
print(b.ndim,b.size,b.shape)
print(a,b)
b = b[:,:,np.newaxis]

print(b.shape)
b = np.expand_dims(b , axis=0)
print(b.shape)

18IT092
1 9 (9,)
2 18 (6, 3)
2 9 (3, 3)
[[1 2 3]
 [2 1 5]
 [2 4 2]] [[0.33775546 0.57751077 0.35324328]
 [0.0712363  0.47003682 0.55974459]
 [0.76076244 0.6843507  0.97963658]]
(3, 3, 1)
(1, 3, 3, 1)


In [ ]:
print("18IT092")
print(c[c>3])
div_by_2 = c[(c%2==0) | (c%4==0)]
print(div_by_2)

18IT092
[5. 4.]
[2. 2. 2. 4. 2.]


In [ ]:
print("18IT092")
a = np.arange(10)
print(a)
sl = a[1:-2]
print(sl)
a = np.arange(2)
b = np.arange(2)
print(np.vstack((a,b)))
print(np.hstack((a,b)))

18IT092
[0 1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7]
[[0 1]
 [0 1]]
[0 1 0 1]


In [ ]:
print("18IT092")
x = np.arange(1,11)
y = np.hsplit(x , 5)
print(y)

18IT092
[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8]), array([ 9, 10])]


In [ ]:
print("18IT092")
b = np.arange(1,11).reshape(5,2)
for i in np.nditer(b):
  print(i , end=' ')
  pass
print()
with np.nditer(b,op_flags=['readwrite']) as i :
  for x in i:
    x[...] = x*2
    pass
    pass
print(b)

18IT092
1 2 3 4 5 6 7 8 9 10 
[[ 2  4]
 [ 6  8]
 [10 12]
 [14 16]
 [18 20]]
